### ISSUE TITLE
Not able to build project after adding  PlayKitYoubora as pod dependency.

### ISSUE THREAD

**Issue by nishu-priya** [kaltura/playkit-ios-youbora#14]
I am using latest version for PlayKitYoubora.
But after pod install, when I build my project, I am getting the error:
**unable to spawn process (Argument list too long) after installing**

Please check.

**Comment by kaltura-hooks** [comment]
Hi @nishu-priya,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by x-NR-x** [comment]
Hi @nishu-priya,

Thank you for contacting us.
What Xcode and Cocoapods versions are you using?
Is this a new project or existing one?

Thanks,
Nilit Danan

**Comment by nishu-priya** [comment]
Hi @x-NR-x , the project is an existing one.
Xcode - 11.3.1
CocoaPod - 1.9.1

**Comment by x-NR-x** [comment]
Hi @nishu-priya,

Sorry for the delay, can you clean the build as well as the Derived Data folder, and try to re-build.
If it doesn't help try to remove the Pods folder and try the pod update again.

By the way, please perform '_pod update_' and not '_pod install_'. 
'_pod install_', for an existing project, installs the pods that where installed at the beginning and are written down in the podfile.lock file for its reference.
You can specifically perform '_pod update PlayKitYoubora_'  if you would like to update only PlayKitYoubora and not the others.

Please update me.

Thanks,
Nilit Danan
